# docker-compose.yml
version: '3.5'

services:
  student-app:
    image: 'student-app:latest'
    depends_on:
      - postgresql
    hostname: student-app
    build: ./
    container_name: student-app
    ports:
      - "8080:8080"

  postgresql:
    image: 'postgres:15.2'
    container_name: "postgresql"
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"